In [1]:
import numpy as np

In [2]:
lst = [[1,2,3],[4,5,6],[7,8,9]]
x = np.array(lst) #Creates an array
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
x.shape #Tells the dimensions of array or matrix

(3, 3)

In [4]:
np.arange(1,100)#Creates list of numbers in the given range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [5]:
np.linspace(1,20,10) #Divids the given range of numbers in the requiered number

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [6]:
arr = np.arange(0,100)

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
arr.shape

(100,)

In [9]:
arr1 = arr.reshape(10,10)#Changes the dimension of the matrix into required dimensions

In [10]:
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [11]:
np.random.random((5,5))#Creates a matrix with required dimensions with randon numbers in it.

array([[0.31332397, 0.64557577, 0.62610471, 0.71793989, 0.80942383],
       [0.48494386, 0.36999229, 0.55169846, 0.89923833, 0.78502168],
       [0.00936021, 0.16818103, 0.40515425, 0.62963521, 0.54798796],
       [0.18096307, 0.89279761, 0.9366994 , 0.25967359, 0.6513062 ],
       [0.10857567, 0.43269274, 0.60204592, 0.68486003, 0.37156399]])

In [12]:
arr1.min()#Gives the minimun value of the given array or list or matrix

0

In [13]:
arr1.max()#Gives max value

99

In [14]:
arr1.argmax()# Gives the position of the maximun value

99

In [15]:
a = arr.reshape(10,10)

In [16]:
a[1,1] #Value in the row1 and col1 

11

In [17]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [18]:
b = a[2:5,2:5]# Gives the all the value in the given range of rows and collumns

In [19]:
b

array([[22, 23, 24],
       [32, 33, 34],
       [42, 43, 44]])